from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('animais/', views.animal_lista, name='animal_lista'),
    path('animais/novo/', views.animal_criar, name='animal_criar'),
    path('animais/<int:pk>/', views.animal_detalhe, name='animal_detalhe'),
    path('animais/<int:pk>/editar/', views.animal_editar, name='animal_editar'),
    path('animais/<int:pk>/deletar/', views.animal_deletar, name='animal_deletar'),
    path('tutores/', views.tutor_lista, name='tutor_lista'),
    path('tutores/novo/', views.tutor_criar, name='tutor_criar'),
    path('tutores/<int:pk>/', views.tutor_detalhe, name='tutor_detalhe'),
    path('tutores/<int:pk>/editar/', views.tutor_editar, name='tutor_editar'),
    path('tutores/<int:pk>/deletar/', views.tutor_deletar, name='tutor_deletar'),
    path('veterinarios/', views.veterinario_lista, name='veterinario_lista'),
    path('veterinarios/novo/', views.veterinario_criar, name='veterinario_criar'),
    path('veterinarios/<int:pk>/', views.veterinario_detalhe, name='veterinario_detalhe'),
    path('veterinarios/<int:pk>/editar/', views.veterinario_editar, name='veterinario_editar'),
    path('veterinarios/<int:pk>/deletar/', views.veterinario_deletar, name='veterinario_deletar'),
    path('servicos/', views.servico_lista, name='servico_lista'),
    path('servicos/novo/', views.servico_criar, name='servico_criar'),
    path('servicos/<int:pk>/', views.servico_detalhe, name='servico_detalhe'),
    path('servicos/<int:pk>/editar/', views.servico_editar, name='servico_editar'),
    path('servicos/<int:pk>/deletar/', views.servico_deletar, name='servico_deletar'),
    path('agendamentos/', views.agendamento_lista, name='agendamento_lista'),
    path('agendamentos/novo/', views.agendamento_criar, name='agendamento_criar'),
    path('agendamentos/<int:pk>/', views.agendamento_detalhe, name='agendamento_detalhe'),
    path('agendamentos/<int:pk>/editar/', views.agendamento_editar, name='agendamento_editar'),
    path('agendamentos/<int:pk>/deletar/', views.agendamento_deletar, name='agendamento_deletar'),
    path('registrar/', views.registrar_usuario, name='registrar_usuario'),
    path('perfil/', views.editar_perfil, name='editar_perfil'),
    path('perfil/senha/', views.alterar_senha, name='alterar_senha'),
]